[package]
name = "beam-server"
description = "Rendezvous server that helps two beam devices find each other"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[lints]
workspace = true

[dependencies]
beam = { path = "../beam" }
clap = { version = "4.6.7", features = ["derive"] }
tokio = { version = "1.53.1", features = ["rt-multi-thread", "net", "macros"] }
